services:

  standalone:
    container_name: milvus-standalone-name
    image: milvusdb/milvus:v2.6.4
    command: ["milvus", "run", "standalone"]
    security_opt:
    - seccomp:unconfined
    environment:
      MQ_TYPE: woodpecker
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/milvus:/var/lib/milvus
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/healthz"]
      interval: 30s
      start_period: 90s
      timeout: 20s
      retries: 3
    ports:
      - "19530:19530"
      - "9091:9091"

  app:
    image: ${APP_IMAGE:-af_agent_local}
    build:
      context: .
      dockerfile: Dockerfile
    container_name: af_app
    depends_on:
      - standalone              # Milvus 준비되면 app 시작
    environment:
      - MILVUS_URI=http://standalone:19530
      - OPENROUTER=${OPENROUTER}
      - OPENROUTER_API_BASE=${OPENROUTER_API_BASE}
      - LANGCHAIN_ENDPOINT=${LANGCHAIN_ENDPOINT}
      - LANGCHAIN_PROJECT=${LANGCHAIN_PROJECT}
      - LANGCHAIN_API_KEY=${LANGCHAIN_API_KEY}
      - KAKAO_API_KEY=${KAKAO_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - .:/app
    ports:
      - 8000:8000

networks:
  default:
    name: milvus
