services:
#   Attu - Milvus GUI 관리 도구
   attu:
     container_name: milvus-attu
     image: zilliz/attu:latest
     environment:
       MILVUS_URL: standalone:19530
     ports:
       - "8001:3000"
     depends_on:
       - standalone
networks:
  default:
    name: milvus
